# Generated by Django 4.1.7 on 2023-04-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_respond_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respond',
            name='text',
            field=models.TextField(verbose_name='Ваше сообщение'),
        ),
        migrations.AlterField(
            model_name='respond',
            name='upload',
            field=models.FileField(null=True, upload_to='uploads/', verbose_name='Загрузите Ваше фото'),
        ),
    ]
