# Generated by Django 4.1.7 on 2023-03-15 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_hosting', '0004_alter_category_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='video_hosting.category'),
        ),
    ]
